openapi: 3.0.2
info:
    title: Tickets-API
    version: 1.0.0
    description: '### This is a Swagger UI for out Tickets API'
paths:
    /venues:
        get:
            tags:
                - Venues
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Venue'
                            examples:
                                List of venues:
                                    value:
                                        -
                                            id: 18
                                            name: some text
                                            location: some text
                                            capacity: 58
                                        -
                                            id: 2
                                            name: some text
                                            location: some text
                                            capacity: 10
                    description: Returns a list of venues
                '500':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                List of venues:
                                    value:
                                        - D3
                                        - Lauluv√§ljak
                    description: Internal server error
            summary: Get list of all venues
            description: Returns a list of all venues
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Venue'
                        examples:
                            Venue:
                                value:
                                    id: 39
                                    name: some text
                                    location: some text
                                    capacity: 54
                required: true
            tags:
                - Venues
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Venue'
                            examples:
                                Venue:
                                    value:
                                        id: 58
                                        name: some text
                                        location: some text
                                        capacity: 86
                    description: Creates a new venue
                '400':
                    description: Bad request
                '500':
                    description: Server error
            summary: Create a venue
            description: Creates a new venue
    /events:
        get:
            tags:
                - Events
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Event'
                            examples:
                                List of events:
                                    value:
                                        -
                                            id: 31
                                            name: some text
                                            description: some text
                                            startDate: some text
                                            endDate: some text
                                            VenueId: 55
                                        -
                                            id: 84
                                            name: some text
                                            description: some text
                                            startDate: some text
                                            endDate: some text
                                            VenueId: 22
                    description: |
                        Returns a list of events
                '500':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                List of events:
                                    value:
                                        - 'VOLT presents: Bou'
                                        - Alchemist
                    description: Server error
            summary: Get a list of all events
            description: Returns a list of all events
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Event'
                        examples:
                            event:
                                value:
                                    id: 0
                                    name: some text
                                    description: some text
                                    startDate: some text
                                    endDate: some text
                                    VenueId: 12
                required: true
            tags:
                - Events
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Event'
                            examples:
                                Event:
                                    value:
                                        id: 25
                                        name: some text
                                        description: some text
                                        startDate: some text
                                        endDate: some text
                                        VenueId: 73
                    description: Creates a new event
                '400':
                    description: Bad request
                '500':
                    description: Server error
            summary: Create an event
            description: Creates a new event
    /tickets:
        get:
            tags:
                - Tickets
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Ticket'
                            examples:
                                List of tickets:
                                    value:
                                        -
                                            id: 8
                                            name: some text
                                            price: 9
                                            purchaseDate: some text
                                            EventId: 36
                                        -
                                            id: 23
                                            name: some text
                                            price: 74
                                            purchaseDate: some text
                                            EventId: 34
                    description: |
                        Returns a list of all ticekts
                '500':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                List of tickets:
                                    value:
                                        - '9.99'
                                        - '7'
                    description: Server error
            summary: Get list of all tickets
            description: Returns a list of all tickets in API
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Ticket'
                        examples:
                            Ticket:
                                value:
                                    id: 74
                                    name: some text
                                    price: 22
                                    purchaseDate: some text
                                    EventId: 33
                required: true
            tags:
                - Tickets
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Ticket'
                            examples:
                                Ticket:
                                    value:
                                        id: 5
                                        name: some text
                                        price: 55
                                        purchaseDate: some text
                                        EventId: 68
                    description: Creates a new ticket
                '404':
                    description: Not found
                '500':
                    description: Server error
            summary: Create a ticket
            description: Creates a new ticket
    '/events/{id}':
        get:
            tags:
                - Events
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Event'
                            examples:
                                Event:
                                    value:
                                        id: 82
                                        name: some text
                                        description: some text
                                        startDate: some text
                                        endDate: some text
                                        VenueId: 33
                    description: Returns full details of a given event
                '404':
                    description: Not found
                '500':
                    description: Server error
            summary: Get full details of events
            description: Returns full details of a given event
        put:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Event'
                        examples:
                            Event:
                                value:
                                    id: 44
                                    name: some text
                                    description: some text
                                    startDate: some text
                                    endDate: some text
                                    VenueId: 35
                required: true
            tags:
                - Events
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '204':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Event'
                            examples:
                                Event:
                                    value:
                                        id: 41
                                        name: some text
                                        description: some text
                                        startDate: some text
                                        endDate: some text
                                        VenueId: 23
                    description: Updates an event
                '404':
                    description: Not found
                '500':
                    description: Server error
            summary: Update an event
            description: Updates an event
        delete:
            tags:
                - Events
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '204':
                    description: Deletes a given event
                '404':
                    description: Not found
            summary: Delete an event
            description: |
                Deletes a given event
    /customers/:
        get:
            tags:
                - Customers
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Customer'
                            examples:
                                Customer:
                                    value:
                                        -
                                            id: 41
                                            name: some text
                                            email: some text
                                            TicketId: 52
                                        -
                                            id: 33
                                            name: some text
                                            email: some text
                                            TicketId: 14
                    description: Returns a list of all customers
                '500':
                    description: Server error
            summary: Get a list of all customers
            description: Returns a list of all customers
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Customer'
                        examples:
                            customers:
                                value:
                                    id: 21
                                    name: some text
                                    email: some text
                                    TicketId: 85
                required: true
            tags:
                - Customers
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Customer'
                            examples:
                                Customer:
                                    value:
                                        id: 59
                                        name: some text
                                        email: some text
                                        TicketId: 87
                    description: Creates a new customer
                '404':
                    description: Not found
                '500':
                    description: Server error
            summary: Create a new customer
            description: Creates a new customer
    '/venues/{id}':
        get:
            tags:
                - Venues
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Venue'
                            examples:
                                Full details of a given venue:
                                    value:
                                        id: 27
                                        name: some text
                                        location: some text
                                        capacity: 76
                    description: Returns full details of a given id venue
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Venue /w+ was not found:
                                    value:
                                        error: Venue \w+ was not found in venue array
                    description: Venue was not found in venues array
                '500':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                Full details of a given venue:
                                    value:
                                        id: 1
                                        name: D3
                                        location: Telliskivi 62/2
                                        capacity: 1500
                    description: Server error
            operationId: id
            summary: Get full details of a venue
            description: Returns full details of a given id venue
        put:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Venue'
                        examples:
                            Venue:
                                value:
                                    id: 65
                                    name: some text
                                    location: some text
                                    capacity: 18
                required: true
            tags:
                - Venues
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '202':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Venue'
                            examples:
                                Venue:
                                    value:
                                        id: 29
                                        name: some text
                                        location: some text
                                        capacity: 72
                    description: Venue updated succesfully
                '404':
                    description: Not found
                '500':
                    description: Server error
            summary: Update a venue
            description: |
                Updates a venue
        delete:
            tags:
                - Venues
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '204':
                    description: Deletes a venue
                '404':
                    description: Not found
            summary: Delete a venue
            description: Deletes a venue
    '/customers/{id}':
        get:
            tags:
                - Customers
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Customer'
                            examples:
                                Customer:
                                    value:
                                        id: 57
                                        name: some text
                                        email: some text
                                        TicketId: 71
                    description: Returns full details of a given customer
                '404':
                    description: Not found
                '500':
                    description: Server error
            summary: Get full details of a customer
            description: Returns full details of a given customer
        put:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Event'
                        examples:
                            customer:
                                value:
                                    id: 70
                                    name: some text
                                    description: some text
                                    startDate: some text
                                    endDate: some text
                                    VenueId: 24
                required: true
            tags:
                - Customers
            responses:
                '204':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Customer'
                            examples:
                                Customer:
                                    value:
                                        id: 92
                                        name: some text
                                        email: some text
                                        TicketId: 30
                    description: Updates a given customer
                '404':
                    description: Not found
                '500':
                    description: Server error
            summary: Update customer
            description: Updates a given customer
        delete:
            tags:
                - Customers
            responses:
                '204':
                    description: Deletes a customer
                '404':
                    description: Not found
            summary: Delete a customer
            description: Deletes a customer
        parameters:
            -
                name: id
                in: path
                required: true
    '/tickets/{id}/':
        get:
            tags:
                - Tickets
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Ticket'
                            examples:
                                Ticket:
                                    value:
                                        id: 2
                                        name: some text
                                        price: 75
                                        purchaseDate: some text
                                        EventId: 76
                    description: |
                        Returns full details of a given ticket
                '404':
                    description: Not found
                '500':
                    description: Server error
            summary: Get full details of a ticket
            description: |
                Returns full details of a given ticket
        put:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Ticket'
                        examples:
                            Ticket:
                                value:
                                    id: 6
                                    name: some text
                                    price: 2
                                    purchaseDate: some text
                                    EventId: 98
                required: true
            tags:
                - Tickets
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '204':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Ticket'
                            examples:
                                Ticket:
                                    value:
                                        id: 86
                                        name: some text
                                        price: 96
                                        purchaseDate: some text
                                        EventId: 61
                    description: Updates a given ticket
                '404':
                    description: Not found
                '500':
                    description: Server error
            summary: Update a ticket
            description: Updates a given ticket
        delete:
            tags:
                - Tickets
            parameters:
                -
                    name: id
                    in: path
                    required: true
            responses:
                '204':
                    description: Deletes a given event
                '404':
                    description: Deletes a given event
            summary: Delete a ticket
            description: Deletes a given ticket
components:
    schemas:
        error:
            title: Root Type for error
            description: ''
            type: object
            properties:
                error:
                    type: string
            example:
                error: Error message.
        Venue:
            title: Root Type for Venue
            description: ''
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                location:
                    type: string
                capacity:
                    format: int32
                    type: integer
            example:
                id: 1
                name: D3
                location: Telliskivi 62/2
                capacity: 1500
        Event:
            title: Root Type for Event
            description: ''
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                description:
                    type: string
                startDate:
                    type: string
                endDate:
                    type: string
                VenueId:
                    format: int32
                    description: ''
                    type: integer
            example:
                id: 1
                name: 'VOLT presents: Bou'
                description: ''
                startDate: '15.09'
                endDate: '16.09'
                VenueId: '1'
        Ticket:
            title: Root Type for Event
            description: ''
            required: []
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                price:
                    format: int32
                    type: integer
                purchaseDate:
                    type: string
                EventId:
                    format: int32
                    type: integer
            example: |-
                {
                    "id": 54,
                    "name": "Kalamees",
                    "price": 87,
                    "purchaseDate": "10.10.2020",
                    "EventId": 53,
                }
        Customer:
            title: Root Type for Event
            description: ''
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                email:
                    type: string
                TicketId:
                    format: int32
                    description: ''
                    type: integer
            example:
                id: 8
                name: Kalamees
                email: kalamees@gmail.com
                TicketId: '1'
